= Workshop Rechtsformen & Projektphase 1

1. Beschreibe dein Projekt. Falls du noch kein Projekt hast, versuche ein passendes zu finden. Erfasse die Leitidee und umschreibe die passende Branche dazu.

* Welche Funktionen/Mehrwert bietet das Produkt/Dienstleistung?
* Welche Voraussetzungen sind notwendig für die Umsetzung?
* Wer sind deine Abnehmer? Und wie viele?
* Worin siehst du den Mehrwert im digitalen Marketing?

2. Evaluiere welche Rechtsform(en) für euer Projekt infrage kommen würde und begründe.
3. Lerne das zefix.ch kenne und versuche einen passenden Namen zu finden. Bei einer bestehenden Firma kannst du deren Eintrag überprüfen.

=== Salutem Therapie
Ich werde als Projekt Salutem Therapie nehmen. Dies ist die Praxis meiner Mutter. Sie ist Kinesiologin und therapeutische Masseurin. Kurz vor Corona hat sie die Praxis eröffnet, leider konnten bald darauf keine Kunden mehr empfangen werden. Die bestehende Website ist damals aus der Not im Schnellverfahren gestaltet worden und erfüllt nicht die modernen Standards.
Die Grundidee ist es nun, den Online Auftritt zu erneuern, und neue Kunden anzusprechen.

* Die Dienstleistung bietet Heilung und Entspannung. Gerade in einsamen Zeiten ist es wichtig die Psyche, den Geist und den Körper gesund zu halten.
* Für die Umsetzung braucht es eine Praxis, welche Vorhanden ist, jedoch etwas liebe benötigt, einen frischen Web-Auftritt, neue Kunden
* Kunden einer Kinesiologie/Massage Praxis sind Menschen welche eine chronische Krankheit haben, von seelische Beschwerden geplagt werden, muskuläre Verspannungen verspüren oder eine Lymphdrainage benötigen. Zurzeit sind dies vorwiegend Menschen im Umfeld meiner Mutter, einige Bekannte von Bekannten.
* Ich sehe den Mehrwert darin, dass die Kunden-Findung vereinfacht werden kann. Vieles spielt sich heute online ab. Zu Zeiten wo man das Haus nur im Notfall verlässt umso mehr. Daher ist die Investition in digitales Marketing wichtig.

Salutem Therapie ist ein Einzelunternehmen. Zu diesem Zeitpunkt ist dies auch das richtige. Susana Chicharro arbeitet alleine und hat auch kein Interesse daran weiter zu expandieren.

* Wie sieht hier die Rechtslage aus? Sollte jemand wegen einer Therapie Beschwerden aufweisen, haftet sie privat dafür?

Meine Suche auf zefix.ch hat ergeben, dass es in der Schweiz noch drei weitere Praxen mit dem lateinischen Wort Salutem im Namen gibt. Da diese aber nicht gleich um die Ecke sind mach ich mir diesbezüglich nicht so grosse Sorgen.













